// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tapmpahlwxsckbamdrms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcG1wYWhsd3hzY2tiYW1kcm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODg1NDUsImV4cCI6MjA2NDc2NDU0NX0.oFYonOMWn_ue-pQMvJMJOF9FKRr491Cx5R3thOM-wZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);